name: ci

on:
  push:
    branches:
      - feature/general-upgrade

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub ğŸ‹
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building the Docker Image ğŸ³ğŸš§
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          file: ci/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/geoffreyturpin:v2
